apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx
  namespace: default
spec:
  dnsNames:
    - zadanie-na-staz-devops.org
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer